### ISSUE TITLE
Not working at all - doesn't show login button

### ISSUE THREAD

**Issue by avatec** [ILDaviz/Opencart-Facebook-Login-3.x#6]
Hi,

After installing, and configure with valid fb app id - login button doesn't show. There is code belowe sign in button, but nothing shows. 

OC 3.0.3.1
Modified default template.

**Comment by ILDaviz** [comment]
It's presents error on modification.log?

**Comment by ILDaviz** [comment]
Hi, I have created a new version! in this version you use the layout to position the login button 🥳
